#!/usr/bin/env bash
# configure web-02 to be identical to web-01 and add header
sudo apt-get -y update
sudo apt-get -y install nginx
mkdir -p /var/www/html
echo "Holberton School" >> "/var/www/html/index.html"
sudo sed -i "25i\ \tadd_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
