#!/usr/bin/env bash
#
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "12i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
