#!/usr/bin/env bash
# handles signals

touch /var/run/holbertonscript.pid
echo "$$" > /var/run/holbertonscript.pid

_term () {
    echo "I hate the kill command"
    rm "/var/run/holbertonscript.pid"
    exit
}
_quit () {
    rm "/var/run/holbertonscript.pid"
    exit
}

trap "Y U no love me?!" SIGINT
trap _term SIGTERM
trap _quit SIGQUIT

while :
do
	echo "To infinity and beyond"
	sleep 2
done
